Batch updates

diff --git a/hosts/all/config/git/hooks/pre-commit b/hosts/all/config/git/hooks/pre-commit
--- a/hosts/all/config/git/hooks/pre-commit
+++ b/hosts/all/config/git/hooks/pre-commit
@@ -16,3 +16,13 @@ if [[ $rb_files ]]; then
         exit 1
     fi
 fi
+
+ts_files=$(git diff --cached --name-only --diff-filter=ACM | grep ".ts$")
+prettier_cmd="prettier -l"
+
+if [[ $ts_files ]]; then
+    if ! $prettier_cmd $ts_files; then
+        echo "Prettier failed on a staged file. Please fix the errors and try again."
+        exit 1
+    fi
+fi
